plugins { id 'com.android.application' }

android {
    namespace 'in.sahitya.reader'
    compileSdk 36
    buildFeatures { buildConfig true }

    defaultConfig {
        applicationId 'in.sahitya.reader'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.4'
    }
}
