package in.sahitya.reader;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfRenderer;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class ReaderActivity extends Activity {
    private LibraryDb db;private Book book,pair;private LinearLayout root,content;private ScrollView scroll;private TextView body,secondary;private int size=19,margin=24;private float spacing=1.35f;private boolean dark=false;private String source="";private int fg,bg;
    private PdfRenderer pdfRenderer;private ParcelFileDescriptor pdfDescriptor;private ImageView pdfImage;private Bitmap pdfBitmap;private int pdfPageIndex=0,chapterIndex=0;private GestureDetector gestures;private boolean menuOpen=false;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new LibraryDb(this);book=db.book(getIntent().getLongExtra("book",-1));long p=getIntent().getLongExtra("pair",-1);if(p!=-1)pair=db.book(p);android.content.SharedPreferences pref=getSharedPreferences("reader_preferences",MODE_PRIVATE);dark=pref.getBoolean("dark",false);size=pref.getInt("size",19);margin=pref.getInt("margin",24);spacing=pref.getFloat("spacing",1.35f);if(book==null){finish();return;}if("CHAPTERS".equals(book.format)){chapterIndex=Math.max(0,Math.min(35,pref.getInt("chapter_"+book.id,book.progress*36/100)));loadChapter();}else if(!"PDF".equals(book.format)){try{source=DocumentText.read(book.path,book.format);}catch(Exception e){source="Unable to read this file. "+e.getMessage();}}gestures=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){@Override public void onLongPress(MotionEvent e){if(e.getX()>getResources().getDisplayMetrics().widthPixels*.25f&&e.getX()<getResources().getDisplayMetrics().widthPixels*.75f&&e.getY()>getResources().getDisplayMetrics().heightPixels*.25f&&e.getY()<getResources().getDisplayMetrics().heightPixels*.75f)showReaderMenu();}@Override public boolean onFling(MotionEvent a,MotionEvent b,float vx,float vy){if(a!=null&&Math.abs(b.getX()-a.getX())>dp(90)&&Math.abs(vx)>Math.abs(vy)*1.3f){navigate(b.getX()<a.getX()?1:-1);return true;}return false;}});render();}
    @Override public boolean dispatchTouchEvent(MotionEvent event){if(gestures!=null&&!menuOpen)gestures.onTouchEvent(event);return super.dispatchTouchEvent(event);}
    private void loadChapter(){try{String name=String.format(Locale.ROOT,"%02d.txt",chapterIndex+1);source=DocumentText.read(new File(book.path,name).getAbsolutePath(),"TXT").trim();}catch(Exception e){source="Unable to read this chapter. "+e.getMessage();}}
    private void colors(){bg=dark?0xff171b18:0xfff7f5ef;fg=dark?0xffeeeae0:0xff292d28;}
    private TextView text(String s,int n,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(n);t.setTextColor(color);return t;}
    private void render(){colors();getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);if(Build.VERSION.SDK_INT>=23){int flags=dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;if(!dark&&Build.VERSION.SDK_INT>=26)flags|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;getWindow().getDecorView().setSystemUiVisibility(flags);}body=null;secondary=null;scroll=null;root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);setContentView(root);if("PDF".equals(book.format))showPdf();else showText();
    }
    private void showText(){scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setVerticalScrollBarEnabled(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));content=new LinearLayout(this);content.setOrientation(pair==null?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);scroll.addView(content);if("CHAPTERS".equals(book.format)){TextView heading=text("गोदान  ·  भाग "+(chapterIndex+1),24,fg);heading.setTypeface(null,Typeface.BOLD);heading.setPadding(dp(margin),dp(28),dp(margin),0);content.addView(heading);}body=text(source,size,fg);body.setTextIsSelectable(true);android.text.SpannableString marked=new android.text.SpannableString(source);for(String excerpt:db.highlights(book.id)){int at=0;while((at=source.indexOf(excerpt,at))>=0){marked.setSpan(new android.text.style.BackgroundColorSpan(dark?0xff655a31:0xffffe59b),at,at+excerpt.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);at+=excerpt.length();}}body.setText(marked);if(pair==null)content.addView(body,new LinearLayout.LayoutParams(-1,-2));else{secondary=text("",size,fg);secondary.setTextIsSelectable(true);try{secondary.setText(DocumentText.read(pair.path,pair.format));}catch(Exception e){secondary.setText("Could not read paired file.");}content.addView(body,new LinearLayout.LayoutParams(0,-2,1));content.addView(secondary,new LinearLayout.LayoutParams(0,-2,1));}style();
        scroll.post(()->{int max=Math.max(1,content.getHeight()-scroll.getHeight());int percent="CHAPTERS".equals(book.format)?getSharedPreferences("reader_preferences",MODE_PRIVATE).getInt("chapter_offset_"+book.id,0):book.progress;scroll.scrollTo(0,max*percent/100);});scroll.setOnScrollChangeListener((View v,int x,int y,int ox,int oy)->{int max=Math.max(1,content.getHeight()-scroll.getHeight());int percent=Math.min(100,y*100/max);if("CHAPTERS".equals(book.format)){getSharedPreferences("reader_preferences",MODE_PRIVATE).edit().putInt("chapter_"+book.id,chapterIndex).putInt("chapter_offset_"+book.id,percent).apply();db.progress(book.id,Math.min(100,(chapterIndex*100+percent)/36));}else db.progress(book.id,percent);});}
    private void style(){colors();root.setBackgroundColor(bg);if(body!=null){body.setTextSize(size);body.setTextColor(fg);body.setLineSpacing(0,spacing);body.setPadding(dp(margin),dp(margin),dp(margin),dp(60));}if(secondary!=null){secondary.setTextSize(size);secondary.setTextColor(fg);secondary.setLineSpacing(0,spacing);secondary.setPadding(dp(margin),dp(margin),dp(margin),dp(60));}}
    private String selected(){if(body==null)return "";int a=body.getSelectionStart(),b=body.getSelectionEnd();if(a>=0&&b>a)return body.getText().subSequence(a,b).toString().trim();return "";}
    private int pos(){return "PDF".equals(book.format)?pdfPageIndex:(scroll==null?0:scroll.getScrollY());}
    private void bookmark(){db.annotate(book.id,"Bookmark","", "",pos());toast("Bookmark saved");}
    private void highlight(){String s=selected();if(s.isEmpty()){toast("Select a passage first, then tap Highlight");return;}db.annotate(book.id,"Highlight",s,"",pos());body.clearFocus();toast("Passage saved to highlights");}
    private void addNote(){String s=selected();EditText input=new EditText(this);input.setHint("Write a note for this passage");new AlertDialog.Builder(this).setTitle("Personal note").setMessage(s.isEmpty()?"Your note will be saved at this reading position.":s).setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{db.annotate(book.id,"Note",s,input.getText().toString(),pos());if(body!=null)body.clearFocus();toast("Note saved");}).show();}
    private void showNotes(){List<String> items=db.annotations(book.id);if(items.isEmpty()){toast("No bookmarks or notes yet");return;}new AlertDialog.Builder(this).setTitle("Bookmarks, highlights & notes").setItems(items.toArray(new String[0]),(d,w)->{}).setPositiveButton("Done",null).show();}
    private void choosePair(){if(pair!=null){new AlertDialog.Builder(this).setMessage("Paired with "+pair.title+". Return to the library to open another pairing.").setPositiveButton("OK",null).show();return;}List<Book> all=db.books("All");ArrayList<Book> candidates=new ArrayList<>();for(Book b:all)if(b.id!=book.id&&("TXT".equals(b.format)||"EPUB".equals(b.format)))candidates.add(b);if(candidates.isEmpty()){toast("Import a TXT or EPUB in the other language first");return;}String[] names=new String[candidates.size()];for(int i=0;i<names.length;i++)names[i]=candidates.get(i).title+"  ·  "+candidates.get(i).language;new AlertDialog.Builder(this).setTitle("Read side by side").setItems(names,(d,w)->{Intent i=new Intent(this,ReaderActivity.class);i.putExtra("book",book.id);i.putExtra("pair",candidates.get(w).id);startActivity(i);}).show();}
    private void showPdf(){try{if(pdfRenderer!=null)pdfRenderer.close();if(pdfDescriptor!=null)pdfDescriptor.close();pdfRenderer=null;pdfDescriptor=ParcelFileDescriptor.open(new File(book.path),ParcelFileDescriptor.MODE_READ_ONLY);pdfRenderer=new PdfRenderer(pdfDescriptor);pdfPageIndex=Math.min(pdfRenderer.getPageCount()-1,book.progress*pdfRenderer.getPageCount()/100);ScrollView sv=new ScrollView(this);sv.setBackgroundColor(bg);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));pdfImage=new ImageView(this);pdfImage.setAdjustViewBounds(true);pdfImage.setBackgroundColor(Color.WHITE);sv.addView(pdfImage);renderPdfPage();}catch(Exception e){TextView error=text("This PDF could not be opened.\n"+e.getMessage(),16,fg);root.addView(error);}}
    private void renderPdfPage(){if(pdfRenderer==null||pdfImage==null)return;PdfRenderer.Page page=pdfRenderer.openPage(pdfPageIndex);int available=Math.max(dp(180),getResources().getDisplayMetrics().widthPixels-dp(12));int width=Math.min(available,page.getWidth()*2);int height=width*page.getHeight()/page.getWidth();Bitmap next=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);next.eraseColor(Color.WHITE);page.render(next,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);page.close();pdfImage.setImageBitmap(next);if(pdfBitmap!=null)pdfBitmap.recycle();pdfBitmap=next;db.progress(book.id,100*(pdfPageIndex+1)/pdfRenderer.getPageCount());}
    private void navigate(int direction){if("CHAPTERS".equals(book.format)){int target=chapterIndex+direction;if(target<0||target>=36)return;chapterIndex=target;getSharedPreferences("reader_preferences",MODE_PRIVATE).edit().putInt("chapter_"+book.id,target).putInt("chapter_offset_"+book.id,0).apply();db.progress(book.id,target*100/36);loadChapter();render();}else if("PDF".equals(book.format)&&pdfRenderer!=null){int target=pdfPageIndex+direction;if(target>=0&&target<pdfRenderer.getPageCount()){pdfPageIndex=target;renderPdfPage();}}}
    private void showContents(){if(!"CHAPTERS".equals(book.format))return;String[] names=new String[36];for(int i=0;i<36;i++)names[i]="भाग "+(i+1);new AlertDialog.Builder(this).setTitle("गोदान · अध्याय").setSingleChoiceItems(names,chapterIndex,(d,w)->{d.dismiss();chapterIndex=w;getSharedPreferences("reader_preferences",MODE_PRIVATE).edit().putInt("chapter_"+book.id,w).putInt("chapter_offset_"+book.id,0).apply();db.progress(book.id,w*100/36);loadChapter();render();}).setNegativeButton("Cancel",null).show();}
    private void showReaderMenu(){if(menuOpen)return;menuOpen=true;ArrayList<String> options=new ArrayList<>();options.add("Back to library");if("CHAPTERS".equals(book.format))options.add("Chapters · "+(chapterIndex+1)+" / 36");if("PDF".equals(book.format)&&pdfRenderer!=null)options.add("Page · "+(pdfPageIndex+1)+" / "+pdfRenderer.getPageCount());if("CHAPTERS".equals(book.format)||"PDF".equals(book.format)){options.add("Previous");options.add("Next");}options.add("Smaller text");options.add("Larger text");options.add("Narrower margins");options.add("Wider margins");options.add("Less line space");options.add("More line space");options.add(dark?"Light theme":"Dark theme");options.add("Bookmark");options.add("Highlight selected text");options.add("Add note");options.add("My notes");options.add("Pair language");new AlertDialog.Builder(this).setTitle(book.title).setItems(options.toArray(new String[0]),(d,w)->{String choice=options.get(w);switch(choice){case "Back to library":finish();break;case "Previous":navigate(-1);break;case "Next":navigate(1);break;case "Smaller text":size=Math.max(14,size-1);style();saveSettings();break;case "Larger text":size=Math.min(34,size+1);style();saveSettings();break;case "Narrower margins":margin=Math.max(8,margin-4);style();saveSettings();break;case "Wider margins":margin=Math.min(52,margin+4);style();saveSettings();break;case "Less line space":spacing=Math.max(1f,spacing-.1f);style();saveSettings();break;case "More line space":spacing=Math.min(2f,spacing+.1f);style();saveSettings();break;case "Light theme":case "Dark theme":dark=!dark;saveSettings();render();break;case "Bookmark":bookmark();break;case "Highlight selected text":highlight();break;case "Add note":addNote();break;case "My notes":showNotes();break;case "Pair language":choosePair();break;default:showContents();}}).setNegativeButton("Keep reading",null).setOnDismissListener(d->menuOpen=false).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void saveSettings(){getSharedPreferences("reader_preferences",MODE_PRIVATE).edit().putBoolean("dark",dark).putInt("size",size).putInt("margin",margin).putFloat("spacing",spacing).apply();}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    @Override protected void onDestroy(){if(pdfBitmap!=null&&!pdfBitmap.isRecycled())pdfBitmap.recycle();try{if(pdfRenderer!=null)pdfRenderer.close();}catch(Exception ignored){}try{if(pdfDescriptor!=null)pdfDescriptor.close();}catch(Exception ignored){}super.onDestroy();}
}
