package in.sahitya.reader;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfRenderer;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class ReaderActivity extends Activity {
    private LibraryDb db;private Book book,pair;private LinearLayout root,toolbar,content;private ScrollView scroll;private TextView body,secondary;private int size=19,margin=24;private float spacing=1.35f;private boolean dark=false;private String source="";private int fg,bg;
    private PdfRenderer pdfRenderer;private ParcelFileDescriptor pdfDescriptor;private ImageView pdfImage;private Bitmap pdfBitmap;private TextView pdfPageLabel;private int pdfPageIndex=0;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new LibraryDb(this);book=db.book(getIntent().getLongExtra("book",-1));long p=getIntent().getLongExtra("pair",-1);if(p!=-1)pair=db.book(p);android.content.SharedPreferences pref=getSharedPreferences("reader_preferences",MODE_PRIVATE);dark=pref.getBoolean("dark",false);size=pref.getInt("size",19);margin=pref.getInt("margin",24);spacing=pref.getFloat("spacing",1.35f);if(book==null){finish();return;}if(!"PDF".equals(book.format)){try{source=DocumentText.read(book.path,book.format);}catch(Exception e){source="Unable to read this file. "+e.getMessage();}}render();}
    private void colors(){bg=dark?0xff171b18:0xfff7f5ef;fg=dark?0xffeeeae0:0xff292d28;}
    private TextView text(String s,int n,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(n);t.setTextColor(color);return t;}
    private void render(){colors();getWindow().setStatusBarColor(dark?0xff171b18:0xfff7f5ef);getWindow().setNavigationBarColor(dark?0xff171b18:0xfff7f5ef);if(Build.VERSION.SDK_INT>=23){int flags=dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;if(!dark&&Build.VERSION.SDK_INT>=26)flags|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;getWindow().getDecorView().setSystemUiVisibility(flags);}root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);setContentView(root);
        toolbar=new LinearLayout(this);toolbar.setGravity(Gravity.CENTER_VERTICAL);toolbar.setPadding(dp(12),dp(8),dp(12),dp(8));toolbar.setBackgroundColor(dark?0xff202722:0xffefede5);root.addView(toolbar,new LinearLayout.LayoutParams(-1,dp(54)));
        TextView back=action("‹",24);toolbar.addView(back);back.setOnClickListener(v->finish());TextView title=text(book.title,16,fg);title.setTypeface(null,Typeface.BOLD);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=dp(10);toolbar.addView(title,tp);
        addAction("A−",()->{size=Math.max(14,size-1);style();saveSettings();});addAction("A+",()->{size=Math.min(34,size+1);style();saveSettings();});addAction("☼",()->{dark=!dark;saveSettings();render();});
        LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER_VERTICAL);controls.setPadding(dp(16),dp(5),dp(16),dp(5));root.addView(controls,new LinearLayout.LayoutParams(-1,dp(42)));
        TextView smaller=action("− margin",13);controls.addView(smaller);smaller.setOnClickListener(v->{margin=Math.max(8,margin-4);style();saveSettings();});TextView space=action("Line  −",13);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,-2,1);sp.leftMargin=dp(8);controls.addView(space,sp);space.setOnClickListener(v->{spacing=Math.max(1f,spacing-.1f);style();saveSettings();});TextView space2=action("Line  +",13);controls.addView(space2);space2.setOnClickListener(v->{spacing=Math.min(2f,spacing+.1f);style();saveSettings();});TextView larger=action("+ margin",13);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-2,-2);mp.leftMargin=dp(8);controls.addView(larger,mp);larger.setOnClickListener(v->{margin=Math.min(52,margin+4);style();saveSettings();});
        toolbar2();if("PDF".equals(book.format))showPdf();else showText();
    }
    private void toolbar2(){LinearLayout row=new LinearLayout(this);row.setPadding(dp(12),dp(2),dp(12),dp(5));row.setGravity(Gravity.CENTER_VERTICAL);root.addView(row,new LinearLayout.LayoutParams(-1,dp(48)));String[] labels={"Bookmark","Highlight","Note","Pair language","My notes"};Runnable[] actions={this::bookmark,this::highlight,this::addNote,this::choosePair,this::showNotes};for(int i=0;i<labels.length;i++){final Runnable r=actions[i];TextView t=action(labels[i],11);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(7),dp(8),dp(7));t.setBackground(round(dark?0xff29332d:0xffe9e7dd,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(34),i==3?1.35f:1);p.rightMargin=dp(5);row.addView(t,p);t.setOnClickListener(v->r.run());}}
    private void showText(){scroll=new ScrollView(this);scroll.setFillViewport(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));content=new LinearLayout(this);content.setOrientation(pair==null?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);scroll.addView(content);body=text(source, size,fg);body.setTextIsSelectable(true);android.text.SpannableString marked=new android.text.SpannableString(source);for(String excerpt:db.highlights(book.id)){int at=0;while((at=source.indexOf(excerpt,at))>=0){marked.setSpan(new android.text.style.BackgroundColorSpan(dark?0xff655a31:0xffffe59b),at,at+excerpt.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);at+=excerpt.length();}}body.setText(marked);if(pair==null)content.addView(body,new LinearLayout.LayoutParams(-1,-2));else{secondary=text("",size,fg);secondary.setTextIsSelectable(true);try{secondary.setText(DocumentText.read(pair.path,pair.format));}catch(Exception e){secondary.setText("Could not read paired file.");}content.addView(body,new LinearLayout.LayoutParams(0,-2,1));content.addView(secondary,new LinearLayout.LayoutParams(0,-2,1));}style();
        scroll.post(()->{int max=Math.max(1,scroll.getChildAt(0).getHeight()-scroll.getHeight());scroll.scrollTo(0,max*book.progress/100);});scroll.setOnScrollChangeListener((View v,int x,int y,int ox,int oy)->{int max=Math.max(1,content.getHeight()-scroll.getHeight());db.progress(book.id,Math.min(100,y*100/max));});}
    private void style(){colors();root.setBackgroundColor(bg);if(body!=null){body.setTextSize(size);body.setTextColor(fg);body.setLineSpacing(dp((int)(size*(spacing-1))),spacing);body.setPadding(dp(margin),dp(margin),dp(margin),dp(60));}if(secondary!=null){secondary.setTextSize(size);secondary.setTextColor(fg);secondary.setLineSpacing(dp((int)(size*(spacing-1))),spacing);secondary.setPadding(dp(margin),dp(margin),dp(margin),dp(60));}}
    private String selected(){if(body==null)return "";int a=body.getSelectionStart(),b=body.getSelectionEnd();if(a>=0&&b>a)return body.getText().subSequence(a,b).toString().trim();return "";}
    private int pos(){return "PDF".equals(book.format)?pdfPageIndex:(scroll==null?0:scroll.getScrollY());}
    private void bookmark(){db.annotate(book.id,"Bookmark","", "",pos());toast("Bookmark saved");}
    private void highlight(){String s=selected();if(s.isEmpty()){toast("Select a passage first, then tap Highlight");return;}db.annotate(book.id,"Highlight",s,"",pos());body.clearFocus();toast("Passage saved to highlights");}
    private void addNote(){String s=selected();EditText input=new EditText(this);input.setHint("Write a note for this passage");new AlertDialog.Builder(this).setTitle("Personal note").setMessage(s.isEmpty()?"Your note will be saved at this reading position.":s).setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{db.annotate(book.id,"Note",s,input.getText().toString(),pos());if(body!=null)body.clearFocus();toast("Note saved");}).show();}
    private void showNotes(){List<String> items=db.annotations(book.id);if(items.isEmpty()){toast("No bookmarks or notes yet");return;}new AlertDialog.Builder(this).setTitle("Bookmarks, highlights & notes").setItems(items.toArray(new String[0]),(d,w)->{}).setPositiveButton("Done",null).show();}
    private void choosePair(){if(pair!=null){new AlertDialog.Builder(this).setMessage("Paired with "+pair.title+". Return to the library to open another pairing.").setPositiveButton("OK",null).show();return;}List<Book> all=db.books("All");ArrayList<Book> candidates=new ArrayList<>();for(Book b:all)if(b.id!=book.id&& !"PDF".equals(b.format))candidates.add(b);if(candidates.isEmpty()){toast("Import a TXT or EPUB in the other language first");return;}String[] names=new String[candidates.size()];for(int i=0;i<names.length;i++)names[i]=candidates.get(i).title+"  ·  "+candidates.get(i).language;new AlertDialog.Builder(this).setTitle("Read side by side").setItems(names,(d,w)->{Intent i=new Intent(this,ReaderActivity.class);i.putExtra("book",book.id);i.putExtra("pair",candidates.get(w).id);startActivity(i);}).show();}
    private void showPdf(){try{pdfDescriptor=ParcelFileDescriptor.open(new File(book.path),ParcelFileDescriptor.MODE_READ_ONLY);pdfRenderer=new PdfRenderer(pdfDescriptor);pdfPageIndex=Math.min(pdfRenderer.getPageCount()-1,book.progress*pdfRenderer.getPageCount()/100);LinearLayout viewer=new LinearLayout(this);viewer.setOrientation(LinearLayout.VERTICAL);root.addView(viewer,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);viewer.addView(nav,new LinearLayout.LayoutParams(-1,dp(48)));TextView prev=action("← Previous",14);nav.addView(prev);pdfPageLabel=text("",14,fg);pdfPageLabel.setGravity(Gravity.CENTER);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);nav.addView(pdfPageLabel,lp);TextView next=action("Next →",14);nav.addView(next);prev.setOnClickListener(v->{if(pdfPageIndex>0){pdfPageIndex--;renderPdfPage();}});next.setOnClickListener(v->{if(pdfPageIndex<pdfRenderer.getPageCount()-1){pdfPageIndex++;renderPdfPage();}});ScrollView sv=new ScrollView(this);sv.setBackgroundColor(0xffdeddd7);viewer.addView(sv,new LinearLayout.LayoutParams(-1,0,1));pdfImage=new ImageView(this);pdfImage.setAdjustViewBounds(true);pdfImage.setBackgroundColor(Color.WHITE);pdfImage.setElevation(dp(2));pdfImage.setPadding(0,0,0,0);sv.addView(pdfImage);renderPdfPage();}catch(Exception e){TextView error=text("This PDF could not be opened.\n"+e.getMessage(),16,fg);root.addView(error);}}
    private void renderPdfPage(){if(pdfRenderer==null||pdfImage==null)return;PdfRenderer.Page page=pdfRenderer.openPage(pdfPageIndex);int available=Math.max(dp(180),getResources().getDisplayMetrics().widthPixels-dp(36));int width=Math.min(available,page.getWidth()*2);int height=width*page.getHeight()/page.getWidth();Bitmap next=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);next.eraseColor(Color.WHITE);page.render(next,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);page.close();pdfImage.setImageBitmap(next);if(pdfBitmap!=null)pdfBitmap.recycle();pdfBitmap=next;pdfPageLabel.setText((pdfPageIndex+1)+" / "+pdfRenderer.getPageCount());db.progress(book.id,100*(pdfPageIndex+1)/pdfRenderer.getPageCount());}
    private void addAction(String label,Runnable r){TextView t=action(label,14);t.setPadding(dp(7),dp(6),dp(7),dp(6));toolbar.addView(t);t.setOnClickListener(v->r.run());}
    private TextView action(String s,int n){return text(s,n,fg);}
    private android.graphics.drawable.GradientDrawable round(int c,int r){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void saveSettings(){getSharedPreferences("reader_preferences",MODE_PRIVATE).edit().putBoolean("dark",dark).putInt("size",size).putInt("margin",margin).putFloat("spacing",spacing).apply();}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    @Override protected void onDestroy(){if(pdfBitmap!=null&&!pdfBitmap.isRecycled())pdfBitmap.recycle();try{if(pdfRenderer!=null)pdfRenderer.close();}catch(Exception ignored){}try{if(pdfDescriptor!=null)pdfDescriptor.close();}catch(Exception ignored){}super.onDestroy();}
}
